version: '2.1'

services:
  kurapika:
    container_name: "kurapika"
    image: kurapika
    build: 
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    command: >
      sh -c "/root/kurapika >> /root/kurapika.log 2>&1"
    ports:
      - 8090:8090